name: nice-slam
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas
  - brotli
  - brotlipy
  - bzip2
  - ca-certificates
  - cffi
  - cryptography=36.0.2
  - cycler
  - dbus
  - embree
  - expat
  - ffmpeg
  - fontconfig
  - fonttools
  - freetype
  - giflib
  - glib
  - gmp
  - gnutls
  - gst-plugins-base
  - gstreamer
  - icu
  - idna
  - jpeg
  - kiwisolver
  - lame
  - lcms2
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libiconv
  - libnsl
  - libpng
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libuv
  - libwebp
  - libwebp-base
  - libxcb
  - libxml2
  - libzlib
  - llvm-openmp
  - lz4-c
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - munkres
  - ncurses
  - nettle
  - ninja
  - numpy-base
  - olefile
  - openh264
  - openssl
  - pcre
  - pillow
  - pip
  - pycparser
  - pyembree
  - pyopenssl=20.0.1
  - pyparsing
  - pyqt
  - pysocks
  - qt
  - readline
  - setuptools
  - sip
  - six
  - sqlite
  - tbb
  - tk
  - tornado
  - typing_extensions
  - wheel
  - xz
  - zlib
  - zstd
  - pip:
    - addict
    - anyio
    - argon2-cffi
    - argon2-cffi-bindings
    - argparse
    - attrs
    - babel
    - backcall
    - beautifulsoup4
    - bleach
    - charset-normalizer
    - cloudpickle
    - colorama
    - dask
    - debugpy
    - decorator
    - defusedxml
    - deprecation
    - entrypoints
    - filelock
    - fsspec
    - gdown
    - imageio
    - imath
    - importlib-metadata
    - importlib-resources
    - ipykernel
    - ipython
    - ipython-genutils
    - ipywidgets
    - jedi
    - jinja2
    - joblib
    - json5
    - jsonschema
    - jupyter-client
    - jupyter-core
    - jupyter-packaging
    - jupyter-server
    - jupyterlab
    - jupyterlab-pygments
    - jupyterlab-server
    - jupyterlab-widgets
    - locket
    - markupsafe
    - mathutils==2.81.2
    - matplotlib-inline
    - mistune
    - nbclassic
    - nbclient
    - nbconvert
    - nbformat
    - nest-asyncio
    - networkx
    - notebook
    - notebook-shim
    - numpy
    - open3d
    - opencv-python
    - openexr
    - packaging
    - pandas
    - pandocfilters
    - parso
    - partd
    - pexpect
    - pickleshare
    - prometheus-client
    - prompt-toolkit
    - psutil
    - ptyprocess
    - pygments
    - pyrsistent
    - pytz
    - pywavelets
    - pyyaml
    - pyzmq
    - rtree
    - scikit-image
    - scikit-learn
    - scipy
    - seaborn
    - send2trash
    - sniffio
    - soupsieve
    - terminado
    - testpath
    - threadpoolctl
    - tifffile
    - tomlkit
    - toolz
    - tqdm
    - traitlets
    - trimesh
    - wcwidth
    - webencodings
    - websocket-client
    - widgetsnbextension
    - zipp